### ISSUE TITLE
Copy function copies all pages with "\n\n" at the end.

### ISSUE THREAD

**Issue by Tikolu** [Tikolu/nettaB#11]
When reading pages from Edit the Text using the [Read](https://github.com/Tikolu/SETTI/wiki/Read-Function) function the pages always get loaded with a very minor difference. The page gets two blank lines at the end. This is a very small issue but I would like pages to load exactly as they are on Edit the Text.

Run the following code:
```python
print(setti.Read("clock"))
```
Then, look at what printed. It is exactly like the page [clock](http://htwins.net/edit/clock), but with "\n\n" at the end.

I have looked everywhere in the code and couldn't fin a reason for this small issue.

**Comment by Tikolu** [comment]
I experimented around with the code a little and it seems that Requests appends two blank lines to everything it gets. Even after loading a blank page I still receive "\n\n". For now, I fixed this in SETTI's code but I would like to fin a better solution soon.

**Comment by lfernsy** [comment]
2 newlines are appended when using /raw; It seems the current solution is the only viable fix.

**Comment by Tikolu** [comment]
Ok. I'll stick with this solution for now.
