### ISSUE TITLE
Wiki shows incorrect command.

### ISSUE THREAD

**Issue by lfernsy** [Tikolu/nettaB#6]
The wiki shows `pip install bs4` but it should be `pip install beautifulsoup4`

"bs4" is a entirely different module, the term "bs4" is just shorthand for "beautifulsoup4"

**Comment by lfernsy** [comment]
I should add that beautifulsoup4 is still imported using "import bs4"

**Comment by Tikolu** [comment]
Sorry, my mistake. I changed it now.
