### ISSUE TITLE
Saving to a file.

### ISSUE THREAD

**Issue by Tikolu** [Tikolu/nettaB#7]
I would like to add a function to create offline backups, in case another [reset](http://htwins.net/edit/itc/wiki/reset) happens, but I am running into an issue with pages with special symbols.

When I try to print the contents of [specialsymbols](http://htwins.net/edit/specialsymbols), all the characters prints correctly.
```python
print(setti.Read("specialsymbols"))
>>> Prints Successfully
```

However, when I try to save it into a file, I get errors.
```python
f = open("file.txt","w")
f.write(setti.Read("specialsymbols"))
>>> UnicodeEncodeError
```

What do I need to do to get the file into the correct encoding?

**Comment by lfernsy** [comment]
```
with open('file.txt', 'w', encoding='utf-8') as f:
    f.write(setti.Read('specialsymbols'))
```

**Comment by Tikolu** [comment]
It was that simple? I feel stupid now.

Ok, thanks.

**Comment by lfernsy** [comment]
When you get a UnicodeDecodeError, there's a 99% chance you have to put 'utf-8' somewhere.
